baseurl = "http://wheelha.us/"
languageCode = "en-us"
title = "Wheelha.us"
destination = "/var/www/wheelhaus/public"

# Define the number of posts per site
paginate = 10

theme = "wheelhaus"

# Theme config

# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/archives/:year/:month/:day/:slug"
	archive = "/archives/"

[params]
    # Tell me who you are
    author = "Wheelha.us"
    bio = "Home is where your bike is"
    location = "Claremont, California"
    site_description = "We are a family that bikes together. Commuting by bike is our passion and we love talking about cargo bikes and riding with kids. We don’t own a car but we are not anti-car. Teaching our community how to enjoy biking and helping others get started is how we roll."
    copyright  = "Wheelha.us"
    avatar = "css/images/avatar.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "About"
    link   = "/about/"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/wheelha_us"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    recent_articles = true
    tags = false
    tag_cloud = false
